### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/margin-analysis#142]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_invoice_margin - By @ljsalvatierra-factorlibre - #163
- [x] account_invoice_margin_sale - By @ljsalvatierra-factorlibre - #165
- [x] product_margin_classification - By @legalsylvain - #169
- [x] product_replenishment_cost - By @amarcosg - #174
- [x] product_standard_margin - By @amarcosg - #172
- [x] sale_margin_delivered - By @pilarvargas-tecnativa - #183
- [ ] sale_margin_delivery_cost - By @dreispt - #191
- [x] sale_margin_security - By @HugoCordobaLeal - #173
- [x] sale_margin_sync - By @Yadier-Tecnativa - #168
- [x] sale_report_margin - By @flalexg - #175

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by ljsalvatierra-factorlibre** [comment]
Hi, i'm going to migrate `account_invoice_margin` and `account_invoice_margin_sale`.

**Comment by hugo-cordoba** [comment]
Migration to 16.0 sale_margin_security https://github.com/OCA/margin-analysis/pull/173

**Comment by amarcosg** [comment]
Hi, im going to migrate to 16.0 -> product_standard_margin [PR](https://github.com/OCA/margin-analysis/pull/172)

**Comment by aliciagaarzo** [comment]
Im working on sale_margin_delivered

**Comment by amarcosg** [comment]
Migration to 16.0 product_replenishment_cost PR: https://github.com/OCA/margin-analysis/pull/174

**Comment by flalexg** [comment]
Migration to 16.0 sale_report_margin https://github.com/OCA/margin-analysis/pull/175

**Comment by hugo-cordoba** [comment]
Good afternoon. 

We were reviewing the migration of the 'sale_order_margin_percent' module, and we have seen that its functionality is already incorporated in the 'sale_margin' module. There is no need to migrate that module.

**Comment by hugo-cordoba** [comment]
MIgration to 16.0 product_pricelist_margin

**Comment by pedrobaeza** [comment]
> Good afternoon.
> 
> We were reviewing the migration of the 'sale_order_margin_percent' module, and we have seen that its functionality is already incorporated in the 'sale_margin' module. There is no need to migrate that module.

@HugoCordobaLeal Then you can add to OpenUgprade in this file https://github.com/OCA/OpenUpgrade/blob/bfb414a90388a8ff405242a3ba836dfa02c92aa3/openupgrade_scripts/apriori.py#L28 for an smooth migration from þrevious versions, and maybe a column variable renaming.

**Comment by hugo-cordoba** [comment]
> We were reviewing the migration of the 'sale_order_margin_percent' module, and we have seen that its functionality is already incorporated in the 'sale_margin' module. There is no need to migrate that module.

@pedrobaeza https://github.com/OCA/OpenUpgrade/pull/3908
