### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/margin-analysis#29]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] product_replenishment_cost - By @nicomacr  - #32
- [ ] product_historical_margin
- [ ] product_cost_incl_costs_with_bom - Assigned to @stephankeller
- [ ] product_cost_incl_costs_without_bom
- [ ] product_stock_cost_field_report
- [ ] product_historical_margin_report
- [ ] product_cost_incl_bom_price_history
- [ ] product_standard_margin
- [ ] product_cost_incl_bom - By @SodexisTeam - #30
- [ ] product_price_history

**Comment by stephankeller** [comment]
We are porting product_cost_incl_bom to v8 and v9.

**Comment by glotsfl** [comment]
@stephankeller Hi Stephan, any update on the V8 of this module? Thanks

**Comment by stephankeller** [comment]
We ported and it is in production for one of our customer.  We need to
contribute it.  We will try to do this within a week or so.

**Comment by glotsfl** [comment]
Ok thanks a lot Stephan. Can you please provide an update once done? That would be very helpful for one of our project...

**Comment by stephankeller** [comment]
@glotsfl you can see the progress right here: https://github.com/sodexis/margin-analysis/tree/8.0_bom_cost

**Comment by atchuthan** [comment]
@glotsfl The migrated version of product_cost_incl_bom for 8.0 is available here: PR https://github.com/OCA/margin-analysis/pull/30

You could try to review the code changes and make comments on it.

**Comment by glotsfl** [comment]
Thanks a lot guys!
