### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/margin-analysis#31]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] product_cost_incl_bom
- [ ] product_cost_incl_bom_price_history
- [ ] product_cost_incl_costs_with_bom
- [ ] product_cost_incl_costs_without_bom
- [ ] product_historical_margin
- [ ] product_historical_margin_report
- [ ] product_price_history
- [x] product_replenishment_cost - By @FFernandez-PlanetaTIC - #47 
- [x] product_standard_margin - By @FFernandez-PlanetaTIC - #49 
- [ ] product_stock_cost_field_report

**Comment by FFernandez-PlanetaTIC** [comment]
product_replenishment_cost #47

**Comment by FFernandez-PlanetaTIC** [comment]
product_standard_margin #49
