### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/margin-analysis#35]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] product_cost_incl_bom
- [ ] product_cost_incl_bom_price_history
- [ ] product_cost_incl_costs_with_bom
- [ ] product_cost_incl_costs_without_bom
- [ ] product_historical_margin
- [ ] product_historical_margin_report
- [ ] product_price_history
- [ ] product_replenishment_cost
- [ ] product_standard_margin
- [ ] product_stock_cost_field_report
- [ ] sale_line_cost_control
- [x] sale_margin_delivered - By @sergio-teruel - #39
